BROKER_BACKEND = "redis"
BROKER_HOST = "redis.CHANGE_THIS.dotcloud.com"
BROKER_PORT = 2894
BROKER_VHOST = 0
BROKER_PASSWORD = "PASSWORD"

CELERY_RESULT_BACKEND = "redis"
REDIS_HOST = "redis.CHANGE_THIS.dotcloud.com"
REDIS_PORT = 2894
REDIS_DB = 0
REDIS_PASSWORD = "PASSWORD"
REDIS_CONNECT_RETRY = True

CELERY_IMPORTS = ('ping',)
